xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    Flow_m3_sec_zscore_norm:
      dims: []
      attrs: {}
      data: 0.4751374423503876
    Flow_m3_sec_zscore_norm_shift18:
      dims: []
      attrs: {}
      data: 0.4752584993839264
    Rain_gauge_1_zscore_norm:
      dims: []
      attrs: {}
      data: 1.0444093942642212
    Rain_gauge_2_zscore_norm:
      dims: []
      attrs: {}
      data: 1.129486322402954
    Rain_gauge_3_zscore_norm:
      dims: []
      attrs: {}
      data: 1.0931296348571777
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    Flow_m3_sec_zscore_norm:
      dims: []
      attrs: {}
      data: -0.08141443133354187
    Flow_m3_sec_zscore_norm_shift18:
      dims: []
      attrs: {}
      data: -0.0813877284526825
    Rain_gauge_1_zscore_norm:
      dims: []
      attrs: {}
      data: -0.0037730277981609106
    Rain_gauge_2_zscore_norm:
      dims: []
      attrs: {}
      data: 0.008840037509799004
    Rain_gauge_3_zscore_norm:
      dims: []
      attrs: {}
      data: 0.0008780408534221351
