autoregressive_inputs:
- Flow_m3_sec_zscore_norm_shift18

batch_size: 512

clip_gradient_norm: 1

clip_targets_to_zero:
- Flow_m3_sec_zscore_norm

data_dir: ..\data\Caravan_for_Omri_N
dataset: caravan

device: cpu

dynamic_inputs:
- Rain_gauge_1_zscore_norm
- Rain_gauge_2_zscore_norm
- Rain_gauge_3_zscore_norm

epochs: 5

experiment_name: test_validation_loss
forcings:
- il

head: regression

hidden_size: 64

initial_forget_bias: 3

lagged_features:
  Flow_m3_sec_zscore_norm:
  - 18
  Rain_gauge_1_zscore_norm:
  - 18
  Rain_gauge_2_zscore_norm:
  - 18
  Rain_gauge_3_zscore_norm:
  - 18

learning_rate: 0.001

log_interval: 1

log_n_figures: 8

log_tensorboard: true

loss: MSE

metrics:
- MSE

model: arlstm

num_workers: 0

optimizer: Adam

output_activation: linear

output_dropout: 0

predict_last_n: 1

save_weights_every: 1

seq_length: 36

target_variables:
- Flow_m3_sec_zscore_norm

use_basin_id_encoding: false

test_basin_file: RT_flood/test_basins.txt
test_end_date: 30/05/2018
test_start_date: 01/10/2017

train_basin_file: RT_flood/test_basins.txt
train_start_date:
- 01/10/2010
train_end_date:
- 30/05/2011

validate_every: 1
validate_n_random_basins: 0

validation_basin_file: RT_flood/test_basins.txt
validation_start_date: 01/10/2015
validation_end_date: 30/05/2016
