dynamic_attributes:
  - snow_depth_water_equivalent_mean
  - surface_net_solar_radiation_mean
  - surface_net_thermal_radiation_mean
  - surface_pressure_mean
  - temperature_2m_mean
  - dewpoint_temperature_2m_mean
  - u_component_of_wind_10m_mean
  - v_component_of_wind_10m_mean
  - volumetric_soil_water_layer_1_mean
  - volumetric_soil_water_layer_2_mean
  - volumetric_soil_water_layer_3_mean
  - volumetric_soil_water_layer_4_mean
  - snow_depth_water_equivalent_min
  - surface_net_solar_radiation_min
  - surface_net_thermal_radiation_min
  - surface_pressure_min
  - temperature_2m_min
  - dewpoint_temperature_2m_min
  - u_component_of_wind_10m_min
  - v_component_of_wind_10m_min
  - volumetric_soil_water_layer_1_min
  - volumetric_soil_water_layer_2_min
  - volumetric_soil_water_layer_3_min
  - volumetric_soil_water_layer_4_min
  - snow_depth_water_equivalent_max
  - surface_net_solar_radiation_max
  - surface_net_thermal_radiation_max
  - surface_pressure_max
  - temperature_2m_max
  - dewpoint_temperature_2m_max
  - u_component_of_wind_10m_max
  - v_component_of_wind_10m_max
  - volumetric_soil_water_layer_1_max
  - volumetric_soil_water_layer_2_max
  - volumetric_soil_water_layer_3_max
  - volumetric_soil_water_layer_4_max
  - total_precipitation_sum
  - potential_evaporation_sum

static_attributes:
  - p_mean
  - pet_mean
  - aridity
  - frac_snow
  - moisture_index
  - seasonality
  - high_prec_freq
  - high_prec_dur
  - low_prec_freq
  - low_prec_dur