allow_subsequent_nan_losses: 100
batch_size: 256
clip_gradient_norm:
commit_hash:
data_dir: ..\data\Caravan
dataset: caravan
device: cpu
dynamic_inputs:
- snow_depth_water_equivalent_mean
- surface_net_solar_radiation_mean
- surface_net_thermal_radiation_mean
- surface_pressure_mean
- temperature_2m_mean
- dewpoint_temperature_2m_mean
- u_component_of_wind_10m_mean
- v_component_of_wind_10m_mean
- volumetric_soil_water_layer_1_mean
- volumetric_soil_water_layer_2_mean
- volumetric_soil_water_layer_3_mean
- volumetric_soil_water_layer_4_mean
- total_precipitation_sum
- potential_evaporation_sum
epochs: 40
experiment_name: all_data_caravan_one_layer
forcings:
- maurer
head: regression
hidden_size: 256
img_log_dir: C:\Users\omrin\Desktop\hydrology research\for work\src\runs\all_data_caravan_one_layer_1411_162356\img_log
initial_forget_bias: 3
learning_rate:
  0: 5e-05
  30: 5e-06
log_interval: 5
log_tensorboard: true
loss: NSE
metrics:
- NSE
- KGE
- FHV
model: cudalstm
num_workers: 4
number_of_basins: 6375
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.11.0
predict_last_n: 1
run_dir: C:\Users\omrin\Desktop\hydrology research\for work\src\runs\all_data_caravan_one_layer_1411_162356
save_validation_results: false
save_weights_every: 1
seed: 587618
seq_length: 365
static_attributes:
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
- moisture_index
- seasonality
- gwt_cm_sav
- ele_mt_sav
- slp_dg_sav
- sgr_dk_sav
- area
- glc_pc_s01
- glc_pc_s02
- glc_pc_s03
- glc_pc_s04
- glc_pc_s06
- glc_pc_s07
- glc_pc_s08
- glc_pc_s09
- glc_pc_s10
- glc_pc_s11
- glc_pc_s12
- glc_pc_s13
- glc_pc_s14
- glc_pc_s15
- glc_pc_s16
- glc_pc_s17
- glc_pc_s18
- glc_pc_s19
- glc_pc_s20
- glc_pc_s21
- glc_pc_s22
- pnv_pc_s01
- pnv_pc_s02
- pnv_pc_s03
- pnv_pc_s04
- pnv_pc_s05
- pnv_pc_s06
- pnv_pc_s07
- pnv_pc_s08
- pnv_pc_s09
- pnv_pc_s10
- pnv_pc_s11
- pnv_pc_s12
- pnv_pc_s13
- pnv_pc_s14
- pnv_pc_s15
statics_embedding:
  hiddens: 10
target_variables:
- streamflow
test_basin_file: caravan_all_basins.txt
test_end_date: 31/12/2000
test_start_date: 01/01/1991
train_basin_file: caravan_all_basins.txt
train_dir: C:\Users\omrin\Desktop\hydrology research\for work\src\runs\all_data_caravan_one_layer_1411_162356\train_data
train_end_date: 31/12/2020
train_start_date: 01/01/2001
validate_every: 1
validate_n_random_basins: 6375
validation_basin_file: caravan_all_basins.txt
validation_end_date: 31/12/1990
validation_start_date: 01/01/1981
