Data:
  Datasets:
    camels: True # True | False | {*choose sub-files*}
    camelsaus: True # True | False | {*choose sub-files*}
    camelsbr: True # True | False | {*choose sub-files*}
    camelscl: True # True | False | {*choose sub-files*}
    camelsgb: True # True | False | {*choose sub-files*}
    hysets: True # True | False | {*choose sub-files*}
    lamah: True # True | False | {*choose sub-files*}
  Attributes:
    caravan: True # True | False | {*choose sub-attributes*}
    hydroatlas: True # True | False | {*choose sub-attributes*}
    other: True # True | False | {*choose sub-attributes*}

Build:
  window_size: 24
  handle_missing_target: 'Drop' # Drop | Avg | Zero
  handle_zero_value: 'Leave' # Leave | Avg | Zero | Clip
