# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: all_data_caravan_one_layer

# place to store run directory (if empty runs are stored in $cwd$/runs/)
run_dir:

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: caravan_all_basins.txt
validation_basin_file: caravan_all_basins.txt
test_basin_file: caravan_all_basins.txt

# training, validation and test time periods (format = 'dd/mm/yyyy')
train_start_date: '01/01/2018'
train_end_date: '31/12/2020'
validation_start_date: '01/01/1989'
validation_end_date: '31/12/1990'
test_start_date: '01/01/1999'
test_end_date: '31/12/2000'

# fixed seed, leave empty to use a random seed
seed:

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 1

# specify how many random basins to use for validation
validate_n_random_basins: 6375

# specify which metrics to calculate during validation (see codebase.evaluation.metrics)
metrics:
- NSE
- KGE
- FHV

# --- Model configuration --------------------------------------------------------------------------

# base model type [lstm, ealstm, cudalstm, embcudalstm, shortcutlstm, dropoutlstm, cudalstminitialh]
# (has to match the if statement in modelzoo/__init__.py)
model: cudalstm

# prediction head [regression, mdn, umal]. Define the head specific parameters below
head: regression

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 256

# Initial bias value of the forget gate
initial_forget_bias: 3

# Dropout applied to the output of the LSTM
output_dropout: 0.4

output_activation: linear

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam, Adadelta]
optimizer: Adam

# specify loss [MSE, NSE, RMSE, UMALLoss, MDNLoss]
loss: NSE

allow_subsequent_nan_losses: 100

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
    0: 5e-5
    30: 5e-6

# Mini-batch size
batch_size: 256

# Number of training epochs
epochs: 40

# If True, clips norm of gradients1
clip_gradient_norm:

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length
predict_last_n: 1

# Length of the input sequence
seq_length: 365

# Number of parallel workers used in the data pipeline
num_workers: 4

# Log the training loss every n steps
log_interval: 5

# If true, writes logging results into tensorboard file
log_tensorboard: True

# Save model weights every n epochs
save_weights_every: 1

# Store the results of the validation to disk
save_validation_results: False

# --- Data configurations --------------------------------------------------------------------------

dataset: caravan

# Path to CAMELS data set
data_dir: ../../data/Caravan

# Forcing product [daymet, maurer, maurer_extended, nldas, nldas_extended]
# can be either a list of forcings or a single forcing product
forcings:
- maurer

# variables to use as time series input (names match the data file column headers)
# Note: In case of multiple input forcing products, you have to append the forcing product behind
# each variable. E.g. 'prcp(mm/day)' of the daymet product is 'prcp(mm/day)_daymet'
dynamic_inputs:
- snow_depth_water_equivalent_mean
- surface_net_solar_radiation_mean
- surface_net_thermal_radiation_mean
- surface_pressure_mean
- temperature_2m_mean
- dewpoint_temperature_2m_mean
- u_component_of_wind_10m_mean
- v_component_of_wind_10m_mean
- volumetric_soil_water_layer_1_mean
- volumetric_soil_water_layer_2_mean
- volumetric_soil_water_layer_3_mean
- volumetric_soil_water_layer_4_mean
- total_precipitation_sum
- potential_evaporation_sum


# which columns to use as target
target_variables:
- streamflow

static_attributes:
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
- moisture_index
- seasonality
- gwt_cm_sav
- ele_mt_sav
- slp_dg_sav
- sgr_dk_sav
- area
- glc_pc_s01
- glc_pc_s02
- glc_pc_s03
- glc_pc_s04
- glc_pc_s06
- glc_pc_s07
- glc_pc_s08
- glc_pc_s09
- glc_pc_s10
- glc_pc_s11
- glc_pc_s12
- glc_pc_s13
- glc_pc_s14
- glc_pc_s15
- glc_pc_s16
- glc_pc_s17
- glc_pc_s18
- glc_pc_s19
- glc_pc_s20
- glc_pc_s21
- glc_pc_s22
- pnv_pc_s01
- pnv_pc_s02
- pnv_pc_s03
- pnv_pc_s04
- pnv_pc_s05
- pnv_pc_s06
- pnv_pc_s07
- pnv_pc_s08
- pnv_pc_s09
- pnv_pc_s10
- pnv_pc_s11
- pnv_pc_s12
- pnv_pc_s13
- pnv_pc_s14
- pnv_pc_s15

statics_embedding:
  hiddens: 10