BASE_ATTRIBUTES:
  sample_path: data\Caravan\timeseries\csv\camels\camels_01022500.csv
  SIZE: 39
  KEYS:
  - date
  names:
  - snow_depth_water_equivalent_mean
  - surface_net_solar_radiation_mean
  - surface_net_thermal_radiation_mean
  - surface_pressure_mean
  - temperature_2m_mean
  - dewpoint_temperature_2m_mean
  - u_component_of_wind_10m_mean
  - v_component_of_wind_10m_mean
  - volumetric_soil_water_layer_1_mean
  - volumetric_soil_water_layer_2_mean
  - volumetric_soil_water_layer_3_mean
  - volumetric_soil_water_layer_4_mean
  - snow_depth_water_equivalent_min
  - surface_net_solar_radiation_min
  - surface_net_thermal_radiation_min
  - surface_pressure_min
  - temperature_2m_min
  - dewpoint_temperature_2m_min
  - u_component_of_wind_10m_min
  - v_component_of_wind_10m_min
  - volumetric_soil_water_layer_1_min
  - volumetric_soil_water_layer_2_min
  - volumetric_soil_water_layer_3_min
  - volumetric_soil_water_layer_4_min
  - snow_depth_water_equivalent_max
  - surface_net_solar_radiation_max
  - surface_net_thermal_radiation_max
  - surface_pressure_max
  - temperature_2m_max
  - dewpoint_temperature_2m_max
  - u_component_of_wind_10m_max
  - v_component_of_wind_10m_max
  - volumetric_soil_water_layer_1_max
  - volumetric_soil_water_layer_2_max
  - volumetric_soil_water_layer_3_max
  - volumetric_soil_water_layer_4_max
  - total_precipitation_sum
  - potential_evaporation_sum
  - streamflow
CAMELS_ATTRIBUTES:
  sample_path: data\Caravan\attributes\camels\attributes_caravan_camels.csv
  SIZE: 10
  KEYS:
  - gauge_id
  names:
  - p_mean
  - pet_mean
  - aridity
  - frac_snow
  - moisture_index
  - seasonality
  - high_prec_freq
  - high_prec_dur
  - low_prec_freq
  - low_prec_dur
HYDROATLAS_ATTRIBUTES:
  sample_path: data\Caravan\attributes\camels\attributes_hydroatlas_camels.csv
  SIZE: 196
  KEYS:
  - gauge_id
  names:
  - sgr_dk_sav
  - glc_pc_s06
  - glc_pc_s07
  - nli_ix_sav
  - glc_pc_s04
  - glc_pc_s05
  - glc_pc_s02
  - rev_mc_usu
  - glc_pc_s03
  - glc_pc_s01
  - pet_mm_syr
  - dor_pc_pva
  - glc_pc_s08
  - glc_pc_s09
  - swc_pc_s09
  - ele_mt_smx
  - tbi_cl_smj
  - swc_pc_s01
  - swc_pc_s02
  - swc_pc_s03
  - swc_pc_s04
  - swc_pc_s05
  - swc_pc_s06
  - swc_pc_s07
  - swc_pc_s08
  - crp_pc_sse
  - glc_pc_s22
  - glc_pc_s20
  - glc_pc_s21
  - wet_pc_sg1
  - wet_pc_sg2
  - pac_pc_sse
  - swc_pc_s10
  - swc_pc_s11
  - swc_pc_s12
  - clz_cl_smj
  - gwt_cm_sav
  - glc_pc_s17
  - glc_pc_s18
  - hft_ix_s93
  - glc_pc_s15
  - ire_pc_sse
  - glc_pc_s16
  - glc_pc_s13
  - prm_pc_sse
  - glc_pc_s14
  - glc_pc_s11
  - glc_pc_s12
  - glc_pc_s10
  - kar_pc_sse
  - slp_dg_sav
  - glc_pc_s19
  - tmp_dc_s07
  - tmp_dc_s08
  - tmp_dc_s05
  - tmp_dc_s06
  - tmp_dc_s09
  - for_pc_sse
  - aet_mm_s06
  - aet_mm_s05
  - aet_mm_s08
  - aet_mm_s07
  - aet_mm_s09
  - tmp_dc_s10
  - tmp_dc_s11
  - aet_mm_s02
  - aet_mm_s01
  - tmp_dc_s12
  - aet_mm_s04
  - aet_mm_s03
  - lit_cl_smj
  - tmp_dc_s03
  - tmp_dc_s04
  - tmp_dc_s01
  - tmp_dc_s02
  - cls_cl_smj
  - pre_mm_syr
  - pnv_pc_s01
  - pnv_pc_s04
  - pnv_pc_s05
  - pnv_pc_s02
  - rdd_mk_sav
  - ele_mt_smn
  - pnv_pc_s03
  - pnv_pc_s08
  - pnv_pc_s09
  - pnv_pc_s06
  - pnv_pc_s07
  - wet_cl_smj
  - snw_pc_syr
  - pnv_pc_s11
  - pnv_pc_s12
  - pnv_pc_s10
  - pnv_pc_s15
  - pnv_pc_s13
  - pnv_pc_s14
  - cmi_ix_syr
  - pet_mm_s11
  - pet_mm_s12
  - pet_mm_s10
  - tmp_dc_smn
  - wet_pc_s08
  - wet_pc_s09
  - slt_pc_sav
  - wet_pc_s02
  - wet_pc_s03
  - wet_pc_s01
  - hdi_ix_sav
  - wet_pc_s06
  - wet_pc_s07
  - wet_pc_s04
  - wet_pc_s05
  - fec_cl_smj
  - glc_cl_smj
  - swc_pc_syr
  - hft_ix_s09
  - soc_th_sav
  - gdp_ud_sav
  - dis_m3_pyr
  - gdp_ud_ssu
  - tmp_dc_smx
  - cly_pc_sav
  - pet_mm_s02
  - pet_mm_s03
  - pet_mm_s01
  - riv_tc_usu
  - snw_pc_smx
  - ppd_pk_sav
  - pet_mm_s08
  - aet_mm_s11
  - pet_mm_s09
  - aet_mm_s10
  - pet_mm_s06
  - pet_mm_s07
  - aet_mm_s12
  - pet_mm_s04
  - pet_mm_s05
  - inu_pc_slt
  - ero_kh_sav
  - aet_mm_syr
  - cmi_ix_s10
  - cmi_ix_s11
  - cmi_ix_s12
  - ari_ix_sav
  - tmp_dc_syr
  - tec_cl_smj
  - ria_ha_usu
  - lkv_mc_usu
  - fmh_cl_smj
  - inu_pc_smn
  - pnv_cl_smj
  - pre_mm_s08
  - pre_mm_s09
  - run_mm_syr
  - pre_mm_s06
  - pre_mm_s07
  - pre_mm_s04
  - pre_mm_s05
  - snd_pc_sav
  - pre_mm_s02
  - pre_mm_s03
  - ele_mt_sav
  - pre_mm_s01
  - urb_pc_sse
  - lka_pc_sse
  - pre_mm_s10
  - dis_m3_pmx
  - snw_pc_s01
  - snw_pc_s02
  - snw_pc_s03
  - snw_pc_s04
  - snw_pc_s05
  - snw_pc_s06
  - gla_pc_sse
  - snw_pc_s07
  - snw_pc_s08
  - snw_pc_s09
  - dis_m3_pmn
  - inu_pc_smx
  - pre_mm_s11
  - pre_mm_s12
  - cmi_ix_s07
  - cmi_ix_s08
  - cmi_ix_s05
  - cmi_ix_s06
  - cmi_ix_s09
  - snw_pc_s10
  - snw_pc_s11
  - snw_pc_s12
  - cmi_ix_s03
  - cmi_ix_s04
  - cmi_ix_s01
  - cmi_ix_s02
  - pst_pc_sse
  - area_fraction_used_for_aggregation
  - pop_ct_usu
OTHER_ATTRIBUTES:
  sample_path: data\Caravan\attributes\camels\attributes_other_camels.csv
  SIZE: 3
  KEYS:
  - gauge_id
  - gauge_name
  - country
  names:
  - gauge_lat
  - gauge_lon
  - area
