autoregressive_inputs:
- Flow_m3_sec_zscore_norm_shift18

batch_size: 512

clip_gradient_norm: 1

clip_targets_to_zero:
- Flow_m3_sec_zscore_norm

data_dir: ..\data\Caravan
dataset: caravan

device: cuda:0

epochs: 30

experiment_name: base_Training
forcings:
- il

head: regression

hidden_size: 128

initial_forget_bias: 3

lagged_features:
  Flow_m3_sec_zscore_norm:
  - 18
  Rain_gauge_1_zscore_norm:
  - 18
  Rain_gauge_2_zscore_norm:
  - 18
  Rain_gauge_3_zscore_norm:
  - 18

learning_rate:
  0: 5e-4
  5: 1e-4
  10: 5e-5
  15: 1e-5
  20: 5e-6
  25: 1e-6

log_interval: 1

log_n_figures: 8

log_tensorboard: true

loss: MSE

metrics:
- MSE

model: arlstm

num_workers: 4

optimizer: Adam

output_activation: linear

output_dropout: 0

predict_last_n: 1

save_weights_every: 5

seq_length: 32

target_variables:
- Flow_m3_sec_zscore_norm

use_basin_id_encoding: false

train_basin_file: RT_flood/basins/all_il_basins.txt
train_start_date:
- 01/10/2010
- 01/10/2011
- 01/10/2012
- 01/10/2013
- 01/10/2014
- 01/10/2015
train_end_date:
- 30/05/2011
- 30/05/2012
- 30/05/2013
- 30/05/2014
- 30/05/2015
- 30/05/2016

validate_every: 5
validate_n_random_basins: 0

validation_basin_file: RT_flood/basins/all_il_basins.txt
validation_start_date: 01/10/2016
validation_end_date: 30/05/2017

test_basin_file: RT_flood/basins/all_il_basins.txt
test_start_date: 01/10/2017
test_end_date: 30/05/2018

dynamic_inputs:
- Rain_gauge_1_zscore_norm
- Rain_gauge_2_zscore_norm
- Rain_gauge_3_zscore_norm

statics_embedding:
  hiddens: 25

static_attributes:
- cmi_ix_s02
- glc_pc_s20
- lka_pc_sse
- glc_pc_s22
- glc_pc_s15
- cmi_ix_s12
- cmi_ix_s01
- pnv_pc_s11
- ele_mt_smn
- cmi_ix_s11
- riv_tc_usu
- area
- glc_pc_s14
- dis_m3_pmn
- glc_pc_s19
- for_pc_sse
- glc_pc_s03
- pre_mm_s09
- inu_pc_smn
- dis_m3_pyr
- ero_kh_sav
- glc_pc_s18
- pnv_pc_s12
- dis_m3_pmx
- pnv_pc_s09
- glc_pc_s16
- urb_pc_sse
- cmi_ix_s03
- glc_pc_s12
- pre_mm_s05
- inu_pc_smx
- crp_pc_sse
- rdd_mk_sav
- sgr_dk_sav
- swc_pc_s10
- pst_pc_sse
- swc_pc_s09
- pre_mm_s04
- aet_mm_s10
- aet_mm_s09
- ari_ix_sav
- swc_pc_s11
- pre_mm_s10
- p_mean
- low_prec_dur
- ele_mt_sav
- swc_pc_s12
- pre_mm_s01
- aet_mm_s11
- pre_mm_s02
- swc_pc_s05
- kar_pc_sse
- swc_pc_syr
- seasonality
- pre_mm_syr
- pre_mm_s12
- swc_pc_s01
- aet_mm_s12
- swc_pc_s02
- run_mm_syr
- pre_mm_s11
- swc_pc_s04
- swc_pc_s03
- pre_mm_s03
- aet_mm_s05
- aet_mm_syr
- aet_mm_s01
- ele_mt_smx
- aet_mm_s02
- aet_mm_s04
- aet_mm_s03
- slp_dg_sav
- hft_ix_s09
- gwt_cm_sav
- cmi_ix_syr
- moisture_index
- pet_mean
- tmp_dc_s01
- cly_pc_sav
- tmp_dc_s02
- cmi_ix_s04
- high_prec_freq
- pet_mm_s01
- tmp_dc_s03
- tmp_dc_s12
- pet_mm_s02
- pet_mm_s12
- pet_mm_s03
- tmp_dc_s04
- pet_mm_s11
- snd_pc_sav
- tmp_dc_s11
- cmi_ix_s10
- pet_mm_s04
- pet_mm_syr
- tmp_dc_syr
- pet_mm_s05
- tmp_dc_s05
- pet_mm_s10
- pet_mm_s09
- low_prec_freq
- tmp_dc_s10
- tmp_dc_s09
- cmi_ix_s05
- high_prec_dur
- cmi_ix_s09
